# Generated by Django 5.2.4 on 2025-08-18 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_is_ordered_cart_is_paid_alter_cart_user_and_more'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='checkout',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='checkout',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['cart', 'status'], name='checkout_ch_cart_id_50aa84_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['checkout_request_id'], name='checkout_ch_checkou_fcb8ce_idx'),
        ),
    ]
